Automattic/vaultpress

- composer.json
- composer.lock
- vaultpress.php
Using jetpack-autoloader will prevent errors when running this plugin alongside Jetpack or any other plugin based on Jetpack packages.
**How to Test**
* Modify `composer.json` to require 1.0 of the Jetpack Logo package
* run `composer update`
* run `composer install`
* Active Vaultpress alongside Jetpack master in your test site
* Go to the Jetpack Dashboard and check that it loads without breakage(Jetpack Master requires a more up to date version of the Jetpack Logo package)
> DNA: Use Jetpack autoloader

- changelog.txt
- readme.txt
- to-test.md
- vaultpress.php
This PR introduces a few changes to get us ready for the Beta:
1. Update the version numbers
2. Move the old changelogs over to a new file
- It makes it easier for translators, they don't need to translate old changelog files.
3. Add a testing file that Beta testers will rely on to test the Beta.
When we push this first release to .org, there are a few new files we won't need to `svn add`:
```
.codeclimate.yml
.editorconfig
.eslines.json
.eslintrc.js
.gitignore
.jshintrc
.npmrc
.nvmrc
.phpcs.xml.dist
.prettierrc
renovate.json
node_modules
vendor/bin
vendor/dealerdirect
vendor/phpcompatibility
vendor/sirbrillig
vendor/squizlabs
vendor/wp-coding-standards
composer.lock
package.json
to-test.md
yarn.lock
```
As we continue to define the release process, we won't have to worry about this list, …
> 2.0 Beta Release

- class-vaultpress.php
Fixes #26
Make space between text box and button consistent with the space between the text and the delete button in the other card.
The buttons are now compact, it wasn't necessary to have the big buttons.
The label of the button that deletes settings has been shorted.
> Make spacing consistent in registration card

- composer.json
- composer.lock
**To test**
1. Run `composer install`
2. The VaultPress admin page should continue to load.
> Autoloader: update to Jetpack Autoloader 1.1.0

- styles.css
Fixes #30 
Previously on Bad Layouts:
It's fixed now:
> Fix duplicated icon and bad layout for progress bars

- package.json
See https://github.com/Automattic/jetpack/pull/12745/ for more info
**to test**
1. run `yarn clean`
2. Still see `composer.lock`
> Composer: do not delete composer.lock when cleaning

- class-vaultpress.php
Fixes #40
This moves the styles to to be enqueued always in the admin, not dependent on specific statuses of the VP plugin. 
Before, core's common.css enqueue was overwriting ours, thus causing the white background. 
After applying this patch, you should always see the error notice with a black background as intended.
> Enqueue scripts in a better place

- class-vaultpress.php
Avoid using the admin_notices hook to display notices in the new VP dashboard,
since that new dashboard expects notices to be displayed inside a custom container.
**to test**
- Start from a site with Jetpack and VaultPress active.
- In VP MC, disable the plan.
- Load all admin pages, and make sure notices are displayed in the right place everywhere.
> Notices: hook into a new vaultpress_notices hook in the VP dash.

- package.json
- readme.txt
- vaultpress.php
Update version numbers so one can use the development version of the plugin without getting any update nags.
> General: update version numbers to start 2.1 cycle

- vaultpress.php
The Jetpack IXR client is now autoloaded:
https://github.com/Automattic/jetpack/pull/13270/
That method can consequently be removed.
**It’s going to need to be improved to handle outdated versions of Jetpack too, I think**
Related discussion: p1567509349053000-slack-akismet
> Jetpack: remove call to deprecated function

- vaultpress.php
Fixes #46
1. Start with a site that is connected to WordPress.com, with VaultPress configured.
2. In the VP wp-admin dashboard, click on the link to reset settings.
3. On the page that reloads, you should not see a link to the VaultPress dashboard in the header.
> Admin Page: do not display a dashboard link if not registered.

- vaultpress.php
Fixes #35
This implements the changes that were suggested in the issue above, to make it clearer to site owners that clicking that button is not without consequences.
**Before**
**After**
> Admin Page: update reset settings card wording.

- class.vaultpress-ixr-ssl-client.php
Fixes #94
Core recently started using the spread operator in the IXR_Client class. Since VaultPress extends that class, we must follow suit and switch to using the spread operator as well.
Since VaultPress requires PHP 5.6+ (like Core), this shouldn't be an issue.
> XML-RPC: avoid warnings caused by spread operator

- .travis.yml
Now that PHP 7.4 is out, let's test VaultPress against it.
Do the tests pass? If so, it should be good to merge.
> Unit Tests: add PHP 7.4 to the list of PHP environments

- composer.json
- composer.lock
Both the Logo package and the Autoloader package have been updated. Let's update them in VaultPress as well.
I'm not quite sure why Renovate stopped automatically creating those PRs; maybe its permissions would need to be updated for this repo.
> Packages: update Automattic packages to latest version

- composer.json
- composer.lock
This new version introduces a fix on Windows environments:
https://github.com/Automattic/Jetpack/pull/16595
* You should still be able to use the plugin, the logo should display nicely in the dashboard's footer.
* The plugin should load nicely when used with the Jetpack plugin.
> Update Autoloader to 2.1.0

- vaultpress.php
This PR updates the conditional to check for a Jetpack version before loading XML-RPC client. 
`Jetpack::load_xml_rpc_client()` was deprecated in 7.7 version, and now we would like to clean up this code in Jetpack.
Jetpack PR: https://github.com/Automattic/jetpack/pull/16434
> Check for Jetpack version before loading Jetpack XML-RPC client

- vaultpress.php
The action names that we're hooking to a callback are wrong, they've changed and we haven't updated it. I've added the new ones and left the old ones for backward compatibility.
> Fix user meta pings

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/gardening.yml
Fixes #114 
This will allow us to do a few things automatically:
- Add assignee for issues which are being worked on, and adds the "In Progress" label.
- Remove Status labels once a PR has been merged.
- Send a Slack Notification to the Design team to request feedback, based on labels applied to a PR.
For more info:
- https://github.com/Automattic/jetpack/pull/19239
- https://github.com/Automattic/action-repo-gardening
Internal reference: p3btAN-1nR-p2
No
* Check actions running on this repo: https://github.com/Automattic/vaultpress/actions
* Check the labels added to #114. 
* See the Design Input Requested label that was added to this PR after I added the Needs Design Review label, and see the matching message: p1617185707038000-slack-C0D96691V
> GitHub actions: add gardening action

- .github/workflows/gardening.yml
Fixes #115
﻿- Gardening action: switch to using a tagged version of the action
- Enable Editorial task as it may be used in this repo as well
* N/A
* No
* See #115 to see that the action still works.
* See if labels are properly removed from this PR when it gets merged.
> Gardening Action: update version and enable Editorial task
